import type { CSSProperties } from 'react';
import type { OrderStatus } from '../types/venue';

type StyleFn<T = boolean | string> = (arg: T) => CSSProperties;

export const S = {
  nav: { display: 'flex', alignItems: 'center', gap: 0, background: '#0A0F1E', borderBottom: '1px solid #1E2A3A', padding: '0 16px' } as CSSProperties,
  brandBlock: { display: 'flex', alignItems: 'center', gap: 10, paddingRight: 16, marginRight: 8, borderRight: '1px solid #1E2A3A' } as CSSProperties,
  brandMark: { fontSize: 14, fontWeight: 800, color: '#F8F9FC', letterSpacing: '0.05em' } as CSSProperties,
  brandAccent: { fontSize: 14, fontWeight: 800, color: '#F5A623', letterSpacing: '0.05em' } as CSSProperties,
  navBtn: ((a: boolean) => ({
    padding: '14px 18px', fontSize: 12, fontWeight: 600, letterSpacing: '0.06em',
    textTransform: 'uppercase', border: 'none', cursor: 'pointer', transition: 'all 0.15s',
    background: 'transparent', color: a ? '#F5A623' : '#8B95A8',
    borderBottom: a ? '2px solid #F5A623' : '2px solid transparent',
  })) as StyleFn<boolean>,
  fanWrap: { background: '#0A0F1E', minHeight: '100vh', color: '#F8F9FC', fontFamily: 'system-ui, -apple-system, sans-serif' } as CSSProperties,
  fanHeader: { background: 'linear-gradient(180deg, #0D1929 0%, #0A0F1E 100%)', padding: '20px 16px 16px', borderBottom: '1px solid #1E2A3A' } as CSSProperties,
  fanHeaderTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 } as CSSProperties,
  liveTag: { display: 'inline-flex', alignItems: 'center', gap: 6, background: '#F5A623', color: '#0A0F1E', fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', padding: '3px 8px', borderRadius: 4 } as CSSProperties,
  liveDot: { width: 6, height: 6, borderRadius: '50%', background: '#0A0F1E', animation: 'pulse 1.5s infinite' } as CSSProperties,
  historyBtn: { background: 'transparent', border: '1px solid #2A3547', color: '#8B95A8', fontSize: 11, fontWeight: 700, padding: '5px 10px', borderRadius: 20, cursor: 'pointer' } as CSSProperties,
  fanTitle: { fontSize: 22, fontWeight: 800, color: '#F8F9FC', marginBottom: 2 } as CSSProperties,
  fanSub: { fontSize: 13, color: '#8B95A8' } as CSSProperties,
  catRow: { display: 'flex', gap: 8, padding: '12px 16px', overflowX: 'auto', borderBottom: '1px solid #1E2A3A' } as CSSProperties,
  catBtn: ((a: boolean) => ({
    padding: '6px 14px', borderRadius: 20, border: a ? '1px solid #F5A623' : '1px solid #2A3547',
    background: a ? '#F5A623' : 'transparent', color: a ? '#0A0F1E' : '#8B95A8',
    fontSize: 12, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap', flexShrink: 0,
  })) as StyleFn<boolean>,
  fulfillRow: { display: 'flex', gap: 8, padding: '12px 16px 0' } as CSSProperties,
  fulfillBtn: ((a: boolean) => ({
    flex: 1, padding: '10px 12px', borderRadius: 10, border: a ? '1px solid #F5A623' : '1px solid #1E2A3A',
    background: a ? '#1A1400' : '#111827', color: a ? '#F5A623' : '#8B95A8',
    fontSize: 12, fontWeight: 700, cursor: 'pointer', textAlign: 'center',
  })) as StyleFn<boolean>,
  seatRow: { display: 'flex', gap: 8, padding: '10px 16px 0' } as CSSProperties,
  seatInput: { flex: 1, background: '#111827', border: '1px solid #1E2A3A', borderRadius: 8, padding: '9px 12px', color: '#F8F9FC', fontSize: 13, outline: 'none' } as CSSProperties,
  tipLabel: { fontSize: 12, color: '#8B95A8', margin: '10px 0 6px' } as CSSProperties,
  tipRow: { display: 'flex', gap: 6 } as CSSProperties,
  tipBtn: ((a: boolean) => ({
    flex: 1, padding: '8px 6px', borderRadius: 8, border: a ? '1px solid #F5A623' : '1px solid #2A3547',
    background: a ? '#1A1400' : 'transparent', color: a ? '#F5A623' : '#8B95A8',
    fontSize: 12, fontWeight: 700, cursor: 'pointer',
  })) as StyleFn<boolean>,
  menuGrid: { padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: 10 } as CSSProperties,
  menuCard: ((inCart: boolean) => ({
    background: inCart ? '#0D1929' : '#111827', border: inCart ? '1px solid #F5A623' : '1px solid #1E2A3A',
    borderRadius: 12, padding: '12px 14px', display: 'flex', alignItems: 'center', gap: 12, cursor: 'pointer',
    transition: 'all 0.15s',
  })) as StyleFn<boolean>,
  menuEmoji: { fontSize: 32, flexShrink: 0 } as CSSProperties,
  menuInfo: { flex: 1, minWidth: 0 } as CSSProperties,
  menuName: { fontSize: 14, fontWeight: 700, color: '#F8F9FC', marginBottom: 2 } as CSSProperties,
  menuDesc: { fontSize: 12, color: '#8B95A8', marginBottom: 4 } as CSSProperties,
  menuPrice: { fontSize: 14, fontWeight: 700, color: '#F5A623' } as CSSProperties,
  popularBadge: { fontSize: 9, fontWeight: 700, color: '#F5A623', border: '1px solid #F5A623', borderRadius: 4, padding: '1px 5px', letterSpacing: '0.06em', marginLeft: 6 } as CSSProperties,
  qtyRow: { display: 'flex', alignItems: 'center', gap: 8 } as CSSProperties,
  qtyBtn: { width: 28, height: 28, borderRadius: '50%', border: '1px solid #2A3547', background: '#1A2335', color: '#F8F9FC', fontSize: 16, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700 } as CSSProperties,
  qtyNum: { fontSize: 14, fontWeight: 700, color: '#F8F9FC', minWidth: 16, textAlign: 'center' } as CSSProperties,
  cartBar: { position: 'sticky', bottom: 0, background: '#0A0F1E', borderTop: '1px solid #1E2A3A', padding: '12px 16px' } as CSSProperties,
  cartBtn: ((has: boolean) => ({
    width: '100%', padding: '14px', borderRadius: 10, border: 'none', cursor: has ? 'pointer' : 'not-allowed',
    background: has ? '#F5A623' : '#1A2335', color: has ? '#0A0F1E' : '#3A4557',
    fontSize: 14, fontWeight: 800, letterSpacing: '0.03em', transition: 'all 0.15s',
  })) as StyleFn<boolean>,
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.8)', zIndex: 100, display: 'flex', alignItems: 'flex-end' } as CSSProperties,
  sheet: { background: '#111827', borderRadius: '20px 20px 0 0', padding: '24px 20px 32px', width: '100%', maxHeight: '80vh', overflowY: 'auto' } as CSSProperties,
  sheetTitle: { fontSize: 18, fontWeight: 800, color: '#F8F9FC', marginBottom: 16 } as CSSProperties,
  lineItem: { display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid #1E2A3A', fontSize: 13, color: '#8B95A8' } as CSSProperties,
  lineTotal: { display: 'flex', justifyContent: 'space-between', padding: '12px 0 0', fontSize: 16, fontWeight: 800, color: '#F8F9FC' } as CSSProperties,
  payBtn: { width: '100%', padding: 14, borderRadius: 10, border: 'none', background: '#F5A623', color: '#0A0F1E', fontSize: 15, fontWeight: 800, cursor: 'pointer', marginTop: 16 } as CSSProperties,
  historyEmpty: { color: '#3A4557', fontSize: 13, textAlign: 'center', padding: '24px 0' } as CSSProperties,
  historyRow: { padding: '10px 0', borderBottom: '1px solid #1E2A3A' } as CSSProperties,
  historyHead: { display: 'flex', justifyContent: 'space-between', fontSize: 13, fontWeight: 700, color: '#F8F9FC' } as CSSProperties,
  historyItems: { fontSize: 12, color: '#8B95A8', margin: '4px 0 8px' } as CSSProperties,
  reorderBtn: { background: 'transparent', border: '1px solid #F5A623', color: '#F5A623', fontSize: 11, fontWeight: 700, padding: '5px 12px', borderRadius: 16, cursor: 'pointer' } as CSSProperties,
  confirmWrap: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '60vh', padding: 24, textAlign: 'center' } as CSSProperties,
  bigEmoji: { fontSize: 64, marginBottom: 16 } as CSSProperties,
  confirmTitle: { fontSize: 24, fontWeight: 800, color: '#F8F9FC', marginBottom: 8 } as CSSProperties,
  confirmSub: { fontSize: 14, color: '#8B95A8', marginBottom: 24, lineHeight: 1.6 } as CSSProperties,
  windowTag: { background: '#F5A623', color: '#0A0F1E', fontSize: 28, fontWeight: 900, padding: '12px 32px', borderRadius: 12, marginBottom: 16, letterSpacing: '0.04em' } as CSSProperties,
  runnerCard: { background: '#111827', border: '1px solid #F5A623', borderRadius: 12, padding: '16px 24px', marginBottom: 16, minWidth: 220 } as CSSProperties,
  runnerName: { fontSize: 18, fontWeight: 800, color: '#F5A623', marginBottom: 4 } as CSSProperties,
  runnerSeat: { fontSize: 12, color: '#8B95A8' } as CSSProperties,
  statusPill: ((s: OrderStatus) => ({
    display: 'inline-block', padding: '6px 16px', borderRadius: 20, fontSize: 12, fontWeight: 700, letterSpacing: '0.06em',
    background: s === 'ready' || s === 'delivered' ? '#2ECC71' : s === 'preparing' ? '#F5A623' : '#2A3547',
    color: s === 'ready' || s === 'delivered' ? '#fff' : s === 'preparing' ? '#0A0F1E' : '#8B95A8',
  })) as StyleFn<OrderStatus>,
  staffWrap: { background: '#060C18', minHeight: '100vh', color: '#F8F9FC', fontFamily: 'system-ui, sans-serif' } as CSSProperties,
  staffHeader: { background: '#0A0F1E', borderBottom: '1px solid #1E2A3A', padding: '16px 20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10 } as CSSProperties,
  staffTitle: { fontSize: 18, fontWeight: 800, color: '#F5A623' } as CSSProperties,
  staffSub: { fontSize: 12, color: '#8B95A8', marginTop: 2 } as CSSProperties,
  filterRow: { display: 'flex', gap: 8, padding: '12px 20px 0' } as CSSProperties,
  filterBtn: ((a: boolean) => ({
    padding: '6px 14px', borderRadius: 20, border: a ? '1px solid #F5A623' : '1px solid #2A3547',
    background: a ? '#F5A623' : 'transparent', color: a ? '#0A0F1E' : '#8B95A8',
    fontSize: 12, fontWeight: 700, cursor: 'pointer',
  })) as StyleFn<boolean>,
  orderGrid: { padding: 16, display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 12 } as CSSProperties,
  orderCard: ((s: OrderStatus) => ({
    background: s === 'ready' ? '#0A2010' : s === 'preparing' ? '#1A1400' : '#111827',
    border: `1px solid ${s === 'ready' ? '#2ECC71' : s === 'preparing' ? '#F5A623' : '#1E2A3A'}`,
    borderRadius: 12, padding: 14, transition: 'all 0.3s',
    animation: s === 'received' ? 'flash 1.6s infinite' : 'none',
  })) as StyleFn<OrderStatus>,
  orderCardHead: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 } as CSSProperties,
  orderId: { fontSize: 18, fontWeight: 900, color: '#F8F9FC', letterSpacing: '0.05em' } as CSSProperties,
  orderMeta: { fontSize: 11, color: '#8B95A8', marginTop: 2 } as CSSProperties,
  windowBadge: ((w: string) => ({
    background: w === 'A' ? '#1A2060' : w === 'B' ? '#1A3A1A' : '#3A1A20',
    color: w === 'A' ? '#7B9EF5' : w === 'B' ? '#2ECC71' : '#F5A623',
    fontSize: 11, fontWeight: 700, padding: '3px 8px', borderRadius: 6, letterSpacing: '0.06em',
  })) as StyleFn<string>,
  deliveryBadge: { background: '#3A1A4A', color: '#C77DFF', fontSize: 11, fontWeight: 700, padding: '3px 8px', borderRadius: 6, letterSpacing: '0.06em' } as CSSProperties,
  deliveryMeta: { fontSize: 11, color: '#C77DFF', marginTop: 4 } as CSSProperties,
  orderItems: { fontSize: 12, color: '#8B95A8', lineHeight: 1.8, marginBottom: 10 } as CSSProperties,
  orderTotal: { fontSize: 16, fontWeight: 800, color: '#F5A623', marginBottom: 10 } as CSSProperties,
  actionBtn: ((s: OrderStatus) => ({
    width: '100%', padding: '10px', borderRadius: 8, border: 'none', cursor: 'pointer', fontSize: 12, fontWeight: 700, letterSpacing: '0.06em',
    background: s === 'received' ? '#F5A623' : s === 'preparing' ? '#2ECC71' : '#9B59B6',
    color: s === 'received' ? '#0A0F1E' : '#fff',
  })) as StyleFn<OrderStatus>,
  analyticsWrap: { background: '#060C18', minHeight: '100vh', color: '#F8F9FC', fontFamily: 'system-ui, sans-serif' } as CSSProperties,
  analyticsHeader: { background: '#0A0F1E', borderBottom: '1px solid #1E2A3A', padding: '20px 24px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12 } as CSSProperties,
  analyticsTitle: { fontSize: 20, fontWeight: 900, color: '#F8F9FC' } as CSSProperties,
  analyticsSub: { fontSize: 13, color: '#8B95A8', marginTop: 4 } as CSSProperties,
  exportBtn: { background: '#1A2335', border: '1px solid #2A3547', color: '#F8F9FC', fontSize: 12, fontWeight: 700, padding: '8px 14px', borderRadius: 8, cursor: 'pointer' } as CSSProperties,
  resetBtn: { background: 'transparent', border: '1px solid #E74C3C', color: '#E74C3C', fontSize: 12, fontWeight: 700, padding: '8px 14px', borderRadius: 8, cursor: 'pointer' } as CSSProperties,
  headerBtns: { display: 'flex', gap: 8, flexWrap: 'wrap' } as CSSProperties,
  syncTag: { fontSize: 11, color: '#5DADE2', marginTop: 6 } as CSSProperties,
  statChip: { background: '#0D1929', border: '1px solid #1E2A3A', borderRadius: 12, padding: '14px 16px', flex: '1 1 160px' } as CSSProperties,
  kpiGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12, padding: '20px 20px 0' } as CSSProperties,
  kpiCard: { background: '#0D1929', border: '1px solid #1E2A3A', borderRadius: 12, padding: '14px 16px' } as CSSProperties,
  kpiLabel: { fontSize: 10, color: '#8B95A8', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 } as CSSProperties,
  kpiValue: { fontSize: 26, fontWeight: 900, color: '#F8F9FC', lineHeight: 1.1, marginBottom: 4 } as CSSProperties,
  kpiDelta: ((pos: boolean) => ({ fontSize: 11, fontWeight: 700, color: pos ? '#2ECC71' : '#E74C3C' })) as StyleFn<boolean>,
  chartSection: { padding: '20px' } as CSSProperties,
  chartTitle: { fontSize: 13, fontWeight: 700, color: '#8B95A8', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 12 } as CSSProperties,
  barWrap: { display: 'flex', flexDirection: 'column', gap: 8 } as CSSProperties,
  barRow: { display: 'flex', alignItems: 'center', gap: 10 } as CSSProperties,
  barLabel: { fontSize: 12, color: '#8B95A8', width: 80, flexShrink: 0, textAlign: 'right' } as CSSProperties,
  barTrack: { flex: 1, height: 24, background: '#1A2335', borderRadius: 6, overflow: 'hidden', position: 'relative' } as CSSProperties,
  barFill: ((w: string, c: string) => ({ height: '100%', width: w, background: c, borderRadius: 6, transition: 'width 0.8s ease', display: 'flex', alignItems: 'center', paddingLeft: 8 })) as StyleFn<string>,
  barVal: { fontSize: 11, fontWeight: 700, color: '#F8F9FC' } as CSSProperties,
  feedSection: { padding: '0 20px 24px' } as CSSProperties,
  feedTitle: { fontSize: 13, fontWeight: 700, color: '#8B95A8', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 12 } as CSSProperties,
  feedItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 0', borderBottom: '1px solid #1E2A3A' } as CSSProperties,
  feedLeft: { display: 'flex', gap: 10, alignItems: 'center' } as CSSProperties,
  feedDot: ((s: OrderStatus) => ({ width: 8, height: 8, borderRadius: '50%', background: s === 'ready' || s === 'delivered' ? '#2ECC71' : s === 'preparing' ? '#F5A623' : '#3A4557', flexShrink: 0 })) as StyleFn<OrderStatus>,
  feedText: { fontSize: 12, color: '#F8F9FC' } as CSSProperties,
  feedSub: { fontSize: 11, color: '#8B95A8', marginTop: 1 } as CSSProperties,
  feedAmt: { fontSize: 13, fontWeight: 700, color: '#F5A623' } as CSSProperties,
  toast: { position: 'fixed', top: 'max(1rem, env(safe-area-inset-top))', left: '50%', transform: 'translateX(-50%)', background: '#111827', border: '1px solid #F5A623', color: '#F8F9FC', fontSize: 13, fontWeight: 700, padding: '10px 18px', borderRadius: 24, zIndex: 200, boxShadow: '0 8px 24px rgba(0,0,0,0.4)', animation: 'toastIn 0.25s ease', maxWidth: 'calc(100vw - 2rem)' } as CSSProperties,
  recapCard: { background: '#0D1929', border: '1px solid #1E2A3A', borderRadius: 12, padding: '16px 18px', lineHeight: 1.6, fontSize: 13, color: '#C9D2E0' } as CSSProperties,
  copyBtn: { background: 'transparent', border: '1px solid #2A3547', color: '#8B95A8', fontSize: 11, fontWeight: 700, padding: '5px 12px', borderRadius: 16, cursor: 'pointer', marginTop: 10 } as CSSProperties,
};